name: Run WDIO Tests and Publish Evidence

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run WDIO tests
        run: npm test

      - name: Ensure evidence report exists
        run: |
          mkdir -p reports/html-reports
          echo "<h1>Nenhum relatório encontrado</h1>" > reports/html-reports/evidencia.html
          if [ -f reports/html-reports/evidencia.html ]; then
            echo "✔ Evidência HTML pronta"
          else
            echo "⚠ Evidência não gerada"
          fi

      - name: Upload evidence artifact
        uses: actions/upload-artifact@v4
        with:
          name: evidencia-html
          path: reports/html-reports/

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/html-reports
          publish_branch: gh-pages
          force_orphan: true
